[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
version_provider = "composer"
update_changelog_on_bump = true
annotated_tag = true
bump_message = "$current_version → $new_version"